const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const read = path => fs.readFileSync(require.resolve(path), 'utf8');
const index = read('../index.html');
const app = read('../js/app.js');
const dashboard = read('../js/pages/dashboard.js');
const countdown = read('../js/pages/countdown.js');
const css = read('../css/style.css');
const store = read('../js/store.js');
const wish = read('../js/pages/wish.js');
const expense = read('../js/pages/expense.js');
const serviceWorker = read('../sw.js');
const timeline = read('../js/pages/timeline.js');

test('学习功能不再提供入口、路由或脚本', () => { assert.doesNotMatch(app + index, /case 'study'|page = 'study'|data-page="study"|pages\/study/); });
test('一级导航包含随手花并按产品顺序排列', () => { assert.match(index, /data-page="expense"/); assert.match(css, /dashboard[^}]*order: 1[\s\S]*wish[^}]*order: 2[\s\S]*expense[^}]*order: 3[\s\S]*note[^}]*order: 4[\s\S]*countdown[^}]*order: 5/); });
test('仪表盘仅保留两格统计和可抉择高亮', () => { assert.match(dashboard, /进行中 · 清单/); assert.match(dashboard, /已累积/); assert.match(dashboard, /个物品已达目标/); assert.doesNotMatch(dashboard, /当前阶段|阶段任务|card-stagger/); });
test('设置不再包含背景功能', () => { assert.match(dashboard, /title: '设置'/); assert.doesNotMatch(dashboard + app + css, /背景图片|has-bg/); });
test('学习和背景旧数据会删除且不再导入导出', () => { assert.match(store, /clearObsoleteData[\s\S]*study[\s\S]*bgImage/); const io = store.match(/exportAll\(\)[\s\S]*?clearAll\(\)/)?.[0] || ''; assert.doesNotMatch(io, /study|bgImage/); });
test('提醒保留复选框有可见原生外观并保存 checked', () => { assert.match(countdown, /cd-keepafter[\s\S]*checked/); assert.match(css, /input\[type="checkbox"\][\s\S]*appearance: auto/); });
test('等待中清单支持提前购买且实际价格可修改', () => { assert.match(wish, /提前购买/); assert.match(wish, /purchase-price/); assert.match(wish, /Store\.purchaseWish/); });
test('随手花区分即时型与清单购买且清单来源只读', () => { assert.match(expense, /即时型/); assert.match(expense, /清单购买/); assert.match(expense, /item\.source === 'quick'/); });
test('离线回退只把应用壳用于导航请求', () => { assert.match(serviceWorker, /daily-lite-v13/); assert.match(serviceWorker, /request\.mode === 'navigate'/); assert.doesNotMatch(serviceWorker, /catch\(\(\) => caches\.match\('\.\/'\)\)/); });
test('时间轴存储脚本随多日计划一同刷新缓存', () => { assert.match(index, /js\/store\.js\?v=13/); assert.match(serviceWorker, /js\/store\.js\?v=13/); });
test('今日计划编辑路由脚本会刷新离线缓存', () => { assert.match(index, /js\/app\.js\?v=9/); assert.match(serviceWorker, /js\/app\.js\?v=9/); });
test('全局导航最右侧包含时间轴入口', () => { assert.match(index, /data-page="timeline"[\s\S]*时间轴/); assert.match(css, /timeline[^}]*order: 6/); });
test('时间轴局部导航提供现在计划和关闭', () => { assert.match(timeline, /现在[\s\S]*计划[\s\S]*关闭/); assert.match(timeline, /location\.hash = '#\/'/); });
test('现在页编辑今日计划而计划标签管理后续计划', () => { assert.match(timeline, /data-action="edit-today">✎ 编辑/); assert.match(timeline, /#\/timeline\/today/); assert.match(timeline, /保存今日计划/); assert.match(app, /hash\.includes\('\/today'\) \? 'today'/); });
test('没有今日计划时以当前时间创建空白编辑内容', () => { assert.match(timeline, /TimelineDomain\.createPlan\('', this\.localMinutes\(\)\)/); assert.doesNotMatch(timeline, /sampleText/); });
test('已保存空计划编辑时也使用当前时间', () => { assert.match(timeline, /this\.plan\.items\.length \? this\.plan\.startTimeMinutes : this\.localMinutes\(\)/); });
test('计划页提供结构化删除、排序和拖拽排序', () => { assert.match(timeline, /data-preview-action="delete"/); assert.match(timeline, /data-preview-action="up"/); assert.match(timeline, /dragstart/); assert.match(timeline, /drop/); });
test('计划页管理后续日期并移除复制与重置按钮', () => { assert.match(timeline, /id="timeline-date"/); assert.match(timeline, /futurePlansHtml/); assert.match(timeline, /保存后续计划/); assert.doesNotMatch(timeline, /复制规范文本|重置今日计划|copy-plan|reset-plan/); });
test('后续计划默认明天但开始时间为空且保存后清空编辑区', () => { assert.match(timeline, /selectedDate = tomorrow; const text = ''; const start = ''/); assert.match(timeline, /Store\.saveTimelinePlan\(result\.plan\)[\s\S]*textarea\.value = ''; input\.value = ''; preview\(\)/); assert.match(timeline, /请选择计划开始时间/); });
test('当前事项区分下一项、逾期和全部完成', () => { assert.match(timeline, /mode: 'overdue'/); assert.match(timeline, /NEXT ·/); assert.match(timeline, /OVERDUE ·/); });
test('当前任务与时间轴位于同一滚动段落', () => { assert.match(timeline, /class="day-scroll"[\s\S]*\$\{currentHtml\}[\s\S]*timeline-head[\s\S]*timeline/); });
test('票据不显示方向箭头', () => { assert.doesNotMatch(timeline, /stub-hint small">[←→]/); });
test('校准使用页面内确认层而不是原生 confirm', () => { assert.match(timeline, /calibration-sheet/); assert.match(timeline, /确认校准/); assert.doesNotMatch(timeline, /if \(!confirm\(`从现在继续/); });
test('结转任务显示昨日结转标签', () => { assert.match(timeline, /昨日结转/); assert.match(timeline, /item\.carriedFrom/); });
test('载入时自动结转昨日未完成任务', () => { assert.match(timeline, /applyCarryover\(\)/); assert.match(timeline, /carriedFromDate === yesterdayDate/); assert.match(timeline, /已将昨日/); });
test('计划页可回看历史计划', () => { assert.match(timeline, /historyPlansHtml/); assert.match(timeline, /history-plans/); assert.match(timeline, /PAST PLANS/); assert.match(timeline, /getTimelinePlans\('0001-01-01'\)/); });
